version: '3'
 
networks:
  mydockerapi-dev:
    driver: bridge 
 
services:
  db:
    image: postgis/postgis:12-master
    container_name: "ubq-db"
    ports:
        - "5430:5432"
    networks:
        - backend    
    env_file: 
        - "backend/.env"
    volumes: 
        - ubq-db-v:/var/lib/postgresql/data

  mydockerapi:
    image: mydockerapi:latest
    depends_on:
      - "postgres_image"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"     
    environment:
      DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=movies;username=postgres;password=postgres"
    networks:
      - mydockerapi-dev  
  
  postgres_image:
    image: postgres:latest
    ports:
      - "5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "movies"
    networks:
      - mydockerapi-dev
volumes:
  db_volume: